---
server:
  contextPath: /todo
---
spring:
  thymeleaf:
    mode: LEGACYHTML5
---
spring:
  profiles: local, default
datasource:
  todoapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  todoapp:
    url: jdbc:mysql://localhost:3306/tikbizapp
    username: myuser
    password: mypassword
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
---
logging:
    level:
       root: INFO
    org.springframework.web: INFO